import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer — BAC Calculator",
  description:
    "Important disclaimer for the BAC Calculator. This tool provides estimates only and should not be relied upon for legal or medical decisions.",
  alternates: {
    canonical: "https://alcoholtrackr.com/disclaimer",
  },
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <Link
        href="/"
        className="text-blue-400 hover:text-blue-300 text-sm mb-6 inline-block"
      >
        ← Back to Calculator
      </Link>

      <h1 className="text-3xl font-bold text-white mb-2">Disclaimer</h1>
      <p className="text-gray-400 text-sm mb-8">
        Last updated: February 23, 2026
      </p>

      <div className="space-y-6 text-gray-300 text-sm leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-white mb-2">
            General Disclaimer
          </h2>
          <p>
            The BAC Calculator available on alcoholtrackr.com (&quot;the
            Website&quot;) is provided for{" "}
            <strong>informational and educational purposes only</strong>. The
            results generated by this tool are{" "}
            <strong>estimates based on average values</strong> and should not be
            considered medically or legally accurate.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">
            No Medical Advice
          </h2>
          <p>
            This Website does not provide medical advice. The BAC estimates
            generated by this calculator are not a substitute for professional
            medical advice, diagnosis, or treatment. Always seek the advice of
            your physician or other qualified health provider with any questions
            you may have regarding alcohol consumption and its effects on your
            health.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">
            No Legal Advice
          </h2>
          <p>
            The results of this calculator cannot and should not be used as
            evidence or defense in any legal proceedings. Legal BAC limits vary
            by jurisdiction and circumstance. This calculator&apos;s results do
            not constitute legal advice and should not be relied upon to
            determine whether it is legal or safe to operate a vehicle or
            machinery.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">
            Accuracy Limitations
          </h2>
          <p>
            While we strive for accuracy using the established Widmark formula,
            actual blood alcohol content can vary significantly due to
            individual factors including but not limited to:
          </p>
          <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
            <li>Individual metabolism rates</li>
            <li>Food consumption before and during drinking</li>
            <li>Medications and health conditions</li>
            <li>Liver function and overall health</li>
            <li>Hydration levels</li>
            <li>Genetic factors</li>
            <li>Fatigue and stress levels</li>
            <li>Rate and pattern of alcohol consumption</li>
          </ul>
          <p className="mt-2">
            Only professional BAC testing equipment (breathalyzers or blood
            tests administered by qualified professionals) can provide accurate
            BAC measurements.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">
            Driving and Safety
          </h2>
          <p className="font-semibold text-yellow-400">
            ⚠️ CRITICAL: Never rely solely on this calculator to determine
            whether it is safe to drive, operate machinery, or engage in any
            activity requiring full cognitive and motor function.
          </p>
          <p className="mt-2">
            The safest policy after consuming any amount of alcohol is to{" "}
            <strong>not drive at all</strong>. Use designated drivers,
            ride-sharing services, public transportation, or stay overnight
            instead. Drunk driving kills — choose alternative transportation
            every time.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">
            Limitation of Liability
          </h2>
          <p>
            The Website operator shall not be held liable for any damages,
            injuries, legal consequences, or other negative outcomes arising
            from the use of or reliance on this calculator. By using this tool,
            you acknowledge and accept that:
          </p>
          <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
            <li>The results are estimates only and may be inaccurate</li>
            <li>
              You are solely responsible for your decisions regarding alcohol
              consumption and driving
            </li>
            <li>
              The Website operator is not liable for any consequences resulting
              from actions taken based on this calculator&apos;s results
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">
            Terms and Conditions
          </h2>
          <div className="space-y-2">
            <p>The Website is provided free of charge.</p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-2">Contact</h2>
          <p>
            If you have any questions about this disclaimer, please{" "}
            <Link
              href="/contact"
              className="text-blue-400 hover:text-blue-300 underline"
            >
              contact us
            </Link>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
